SUMMARY = "EPICS SNL sequencer"
DESCRIPTION = "The EPICS State Notation Language sequencer: the snc compiler and \
the seq runtime library."
HOMEPAGE = "https://github.com/epics-modules/sequencer"
LICENSE = "EPICS"
LIC_FILES_CHKSUM = "file://LICENSE;md5=9738eff23564c3683d154e44cc154fbb"
PV = "2.2.9+git"
SRC_URI = "git://github.com/epics-modules/sequencer;protocol=https;nobranch=1"
# Upstream tag R2-2-9.
# master, de4f7c21fb73 as of 2026-09-14.
SRCREV = "de4f7c21fb73a4fe780fa25c78d725ac050409de"
S = "${WORKDIR}/git"
inherit epics-module
EPICS_MODULE_NAME = "seq"
# snc is a host tool that dependent IOC recipes run to compile .st programs,
# so build the host pass and stage the host bin/lib into the sysroot.
EPICS_HOST_PASS = "1"
EPICS_STAGE_HOST_TOOLS = "1"
# snc's lexer.c is generated by re2c (configure/CONFIG_SITE expects re2c on
# the PATH of the build tasks).
DEPENDS += "re2c-native"
