SUMMARY = "EPICS Base"
DESCRIPTION = "Experimental Physics and Industrial Control System Base"
HOMEPAGE = "https://epics-controls.org/"

# EPICS Base uses its own permissive license.
LICENSE = "EPICS"
LIC_FILES_CHKSUM = "file://LICENSE;md5=2eeea17a15fc6ba8501fdcec09b854dc"

PV = "7.0.10"

SRC_URI = "git://github.com/epics-base/epics-base.git;protocol=https;branch=7.0"
SRCREV = "bf11a0c31c919ba85ba2e23b72bcf0b5f9f62e77"
S = "${WORKDIR}/git"

inherit epics-module

# EPICS Base is what every module builds against rather than a module itself:
# it has no configure/RELEASE and its host pass produces the tools that module
# builds run.
EPICS_MODULE_NAME = "base"
EPICS_DEPENDS_BASE = ""
EPICS_WRITE_RELEASE = "0"
EPICS_HOST_PASS = "1"
# libCom.so links libreadline, which the automatic shlibs dependency scan does
# not record for this layout, so the runtime dependency is declared explicitly.
EPICS_RDEPENDS = "perl readline"

# Base reads the target toolchain settings from its own configure/os directory;
# modules use configure/CONFIG_SITE.$(host).$(T_A) instead.
EPICS_CONFIG_SITE_FILE = "configure/os/CONFIG_SITE.${EPICS_HOST_ARCH}.${EPICS_TARGET_ARCH}"

# The shared helper copies the architecture-independent part; the target
# bin/lib trees are installed filtered in do_install below.
EPICS_INSTALL_SUBDIRS = "cfg configure db dbd doc html include templates"

DEPENDS += "readline ncurses"

do_configure() {
    install -d ${S}/configure

    cat > ${S}/configure/CONFIG_SITE <<EOF
# Generated by BitBake for PetaLinux.
CROSS_COMPILER_TARGET_ARCHS = ${EPICS_TARGET_ARCH}
EPICS_HOST_ARCH = ${EPICS_HOST_ARCH}
INSTALL_LOCATION = ${S}
FINAL_LOCATION = ${EPICS_PREFIX}/base-${PV}
# Build both shared (.so) and static (.a) libraries. Shared libraries are
# required for on-target development; static archives are kept for
# applications that link statically.
SHARED_LIBRARIES = YES
STATIC_BUILD = YES
EOF

    epics_generate_config_site
}

do_install() {
    install_dir=${D}${EPICS_PREFIX}/${EPICS_MODULE_NAME}-${EPICS_MODULE_VERSION}
    install -d ${install_dir}

    # Copy common EPICS files from the compile install tree.
    epics_install_subdirs ${install_dir}

    # The cross toolchain settings generated during the build embed the
    # build-host sysroot path. Dependent module recipes generate their own
    # settings, so ship a deliberate placeholder instead of build paths.
    cat > ${install_dir}/configure/os/CONFIG_SITE.${EPICS_HOST_ARCH}.${EPICS_TARGET_ARCH} <<EOF
# Generated by BitBake during the cross build. The compiler commands contain
# build-host paths and are regenerated by every dependent module recipe.
EOF

    # Keep architecture-independent Perl modules only. The build can place
    # host-native XS modules such as libCap5.so under lib/perl; those are not
    # usable on the target and must not enter the package.
    if [ -d ${S}/lib/perl ]; then
        find ${S}/lib/perl -type f \( -name '*.pm' -o -name '*.pl' \) -print | \
            while read -r module; do
                relative=${module#${S}/lib/perl/}
                install -D -m 0644 "${module}" \
                    "${install_dir}/lib/perl/${relative}"
            done
    fi

    # Ship target binaries and libraries only. Host binaries/libraries stay
    # out of ${D} entirely: they are staged into the sysroot after packaging
    # (see epics_stage_host_tools below).
    for subdir in bin lib; do
        if [ -d ${S}/${subdir}/${EPICS_TARGET_ARCH} ]; then
            install -d ${install_dir}/${subdir}/${EPICS_TARGET_ARCH}
            cp -R --no-preserve=ownership ${S}/${subdir}/${EPICS_TARGET_ARCH}/. \
                ${install_dir}/${subdir}/${EPICS_TARGET_ARCH}/
        fi
    done

    # EPICS 7.0.10 keeps architecture-independent scripts in src/tools. A
    # cross build does not guarantee that they are copied to bin/<host-arch>,
    # so do not make packaging depend on that build-side layout.
    install -d ${install_dir}/bin/${EPICS_TARGET_ARCH}
    for script in ${S}/src/tools/*.pl ${S}/src/tools/*.py; do
        [ -f "${script}" ] || continue
        install -m 0755 "${script}" ${install_dir}/bin/${EPICS_TARGET_ARCH}/
    done

    # EPICS 7.0.10 has one script with /bin/env while target images normally
    # provide /usr/bin/perl. Use the target Perl path directly.
    sed -i \
        -e '1s|^#! */bin/env perl$|#!/usr/bin/perl|' \
        -e '1s|^#! */usr/bin/env perl$|#!/usr/bin/perl|' \
        ${install_dir}/bin/${EPICS_TARGET_ARCH}/*.pl

    epics_scrub_build_paths ${install_dir}
    epics_install_symlink

    install -d ${D}${sysconfdir}/profile.d
    # Quoted heredoc delimiter: BitBake expands the recipe variables
    # (${EPICS_PREFIX}, ${PV}, ...) while the runtime shell expands the
    # unbraced $PATH / $LD_LIBRARY_PATH references on the target. Braced
    # ${PATH} must not appear here: BitBake would expand it to the build
    # host PATH and bake TMPDIR paths into the target file.
    cat > ${D}${sysconfdir}/profile.d/epics.sh <<'EOF'
export EPICS_PREFIX=${EPICS_PREFIX}
export EPICS_BASE=${EPICS_PREFIX}/base
export EPICS_BASE_VERSION=${EPICS_PREFIX}/base-${PV}
export EPICS_BASE_BIN=$EPICS_BASE/bin/${EPICS_TARGET_ARCH}
export EPICS_BASE_LIB=$EPICS_BASE/lib/${EPICS_TARGET_ARCH}
export EPICS_TARGET_ARCH=${EPICS_TARGET_ARCH}
export EPICS_HOST_ARCH=${EPICS_TARGET_ARCH}
export PATH=$EPICS_BASE_BIN:$PATH
export LD_LIBRARY_PATH=$EPICS_BASE_LIB:$LD_LIBRARY_PATH
export PERL5LIB=$EPICS_BASE/lib/perl:$PERL5LIB
EOF
}

FILES:${PN} += "${sysconfdir}/profile.d/epics.sh"

# Dependent module recipes run the host-architecture Base tools
# (EPICS_BASE_HOST_BIN, exposed as TOOLS) while generating headers and version
# files, so those tools must be present in their sysroot. They are copied into
# the sysroot after the standard preprocessing, which keeps them out of every
# package and prevents the target strip/objcopy from being applied to
# host-architecture binaries.
epics_stage_host_tools() {
    host_dir=${SYSROOT_DESTDIR}${EPICS_PREFIX}/${EPICS_MODULE_NAME}-${EPICS_MODULE_VERSION}
    install -d ${host_dir}/bin/${EPICS_HOST_ARCH}
    cp -R --no-preserve=ownership ${S}/bin/${EPICS_HOST_ARCH}/. \
        ${host_dir}/bin/${EPICS_HOST_ARCH}/
    if [ -d ${S}/lib/${EPICS_HOST_ARCH} ]; then
        install -d ${host_dir}/lib/${EPICS_HOST_ARCH}
        cp -R --no-preserve=ownership ${S}/lib/${EPICS_HOST_ARCH}/. \
            ${host_dir}/lib/${EPICS_HOST_ARCH}/
    fi
}
SYSROOT_PREPROCESS_FUNCS:append = " epics_stage_host_tools"
