SUMMARY = "EPICS Base"
DESCRIPTION = "Experimental Physics and Industrial Control System Base"
HOMEPAGE = "https://epics-controls.org/"

# EPICS Base uses its own permissive license.
LICENSE = "EPICS"
LIC_FILES_CHKSUM = "file://LICENSE;md5=2eeea17a15fc6ba8501fdcec09b854dc"

PV = "7.0.10"

# EPICS Base bundles PV Access (pvData, pvAccess, normativeTypes, pvaClient,
# pvDatabase, pva2pva) as git submodules. Set to "0" for a core-only build
# (no libpvAccess/softIocPVA/pvget/QSRV); the PVA bundle is then neither
# fetched nor built.
#
# The switch selects the fetcher: gitsm checks the submodules out, plain git
# leaves the submodule directories empty. EPICS' configure/RULES_MODULES only
# adds checked-out submodules to DIRS, so an empty directory is skipped
# cleanly rather than failing the build.
EPICS_PVA_ENABLE ?= "1"

SRC_URI = "${@bb.utils.contains('EPICS_PVA_ENABLE', '1', 'gitsm', 'git', d)}://github.com/epics-base/epics-base.git;protocol=https;branch=7.0"
SRCREV = "bf11a0c31c919ba85ba2e23b72bcf0b5f9f62e77"
S = "${WORKDIR}/git"

inherit epics-module

# EPICS Base is what every module builds against rather than a module itself:
# it has no configure/RELEASE and its host pass produces the tools that module
# builds run.
EPICS_MODULE_NAME = "base"
# EPICS Base has always installed at ${EPICS_PREFIX}/base[-<ver>], not under
# the modules/ subdirectory used by support modules.
EPICS_INSTALL_BASE = "${EPICS_PREFIX}"
EPICS_DEPENDS_BASE = ""
EPICS_WRITE_RELEASE = "0"
EPICS_HOST_PASS = "1"
# libCom.so links libreadline, which the automatic shlibs dependency scan does
# not record for this layout, so the runtime dependency is declared explicitly.
EPICS_RDEPENDS = "perl readline"

# Base reads the target toolchain settings from its own configure/os directory;
# modules use configure/CONFIG_SITE.$(host).$(T_A) instead.
EPICS_CONFIG_SITE_FILE = "configure/os/CONFIG_SITE.${EPICS_HOST_ARCH}.${EPICS_TARGET_ARCH}"

# The shared helper copies the architecture-independent part; the target
# bin/lib trees are installed filtered in do_install below.
EPICS_INSTALL_SUBDIRS = "cfg configure db dbd doc html include templates"

DEPENDS += "readline ncurses"

do_configure() {
    install -d ${S}/configure

    cat > ${S}/configure/CONFIG_SITE <<EOF
# Generated by BitBake for PetaLinux.
CROSS_COMPILER_TARGET_ARCHS = ${EPICS_TARGET_ARCH}
EPICS_HOST_ARCH = ${EPICS_HOST_ARCH}
INSTALL_LOCATION = ${S}
FINAL_LOCATION = ${EPICS_PREFIX}/base-${PV}
# Build both shared (.so) and static (.a) libraries. Shared libraries are
# required for on-target development; static archives are kept for
# applications that link statically.
SHARED_LIBRARIES = YES
STATIC_BUILD = YES
EOF

    epics_generate_config_site

    # EPICS marks these programs as host-only (PROD_HOST), but on-target
    # development needs them on the target:
    #   msi          expands .db templates and .substitutions files while
    #                building IOCs and modules (MSI3_15 in RULES.Db)
    #   iocLogServer is the log daemon
    # Reclassify them as IOC programs so the cross target pass builds them.
    # The guard leaves the host pass untouched: there they are already built
    # through PROD_HOST.
    if [ "${EPICS_TARGET_ARCH}" != "${EPICS_HOST_ARCH}" ]; then
        for target in \
            "modules/database/src/ioc/dbtemplate/Makefile:msi" \
            "modules/libcom/src/log/Makefile:iocLogServer"; do
            makefile=${target%:*}
            program=${target#*:}
            cat >> ${S}/${makefile} <<EOF

# Added by BitBake: build this host-only program for the cross target as well,
# so it is usable when developing on the target itself.
ifneq (\$(EPICS_HOST_ARCH),\$(T_A))
PROD_IOC += ${program}
endif
EOF
        done
    fi
}

do_install() {
    install_dir=${D}${EPICS_INSTALL_BASE}/${EPICS_MODULE_NAME}-${EPICS_MODULE_VERSION}
    install -d ${install_dir}

    # Copy common EPICS files from the compile install tree.
    epics_install_subdirs ${install_dir}

    # The installed CONFIG_SITE must not carry cross-build settings. Base's
    # configure/CONFIG includes it on every build, and EPICS_HOST_ARCH /
    # CROSS_COMPILER_TARGET_ARCHS / INSTALL_LOCATION here would force every
    # on-target build to cross-compile from the build host (and look for tools
    # under bin/<build-host-arch>). Ship the library defaults an EPICS install
    # provides instead. STATIC_BUILD=NO makes executables link the shared
    # libraries, so they resolve e.g. libCom's readline dependency normally.
    cat > ${install_dir}/configure/CONFIG_SITE <<'EOF'
# EPICS Base site configuration, installed for the target.
#
# Do not set EPICS_HOST_ARCH, CROSS_COMPILER_TARGET_ARCHS or INSTALL_LOCATION
# here: this file is included by every build, including on-target builds, and
# those are properties of the build host, not of the installed Base.
SHARED_LIBRARIES = YES
STATIC_BUILD = NO
EOF

    # configure/ is copied wholesale from the build tree; drop its build
    # output directories so nothing stale ships.
    rm -rf ${install_dir}/configure/O.*

    # The cross toolchain settings generated during the build embed the
    # build-host sysroot path. Dependent module recipes generate their own
    # settings, so ship a deliberate placeholder instead of build paths.
    cat > ${install_dir}/configure/os/CONFIG_SITE.${EPICS_HOST_ARCH}.${EPICS_TARGET_ARCH} <<EOF
# Generated by BitBake during the cross build. The compiler commands contain
# build-host paths and are regenerated by every dependent module recipe.
EOF

    # Keep architecture-independent Perl modules only. The build can place
    # host-native XS modules such as libCap5.so under lib/perl; those are not
    # usable on the target and must not enter the package.
    if [ -d ${S}/lib/perl ]; then
        find ${S}/lib/perl -type f \( -name '*.pm' -o -name '*.pl' \) -print | \
            while read -r module; do
                relative=${module#${S}/lib/perl/}
                install -D -m 0644 "${module}" \
                    "${install_dir}/lib/perl/${relative}"
            done
    fi

    # Ship target binaries and libraries only. Host binaries/libraries stay
    # out of ${D} entirely: they are staged into the sysroot after packaging
    # (see epics_stage_host_tools below).
    for subdir in bin lib; do
        if [ -d ${S}/${subdir}/${EPICS_TARGET_ARCH} ]; then
            install -d ${install_dir}/${subdir}/${EPICS_TARGET_ARCH}
            cp -R --no-preserve=ownership ${S}/${subdir}/${EPICS_TARGET_ARCH}/. \
                ${install_dir}/${subdir}/${EPICS_TARGET_ARCH}/
        fi
    done

    # EPICS installs its build tooling (Perl/Python/shell scripts) into
    # bin/<host-arch> only, so a cross build leaves the target without the
    # scripts needed to create and build IOCs and modules on the target itself
    # (makeBaseApp.pl, registerRecordDeviceDriver.pl, dbdExpand.pl, ...).
    # Copy the architecture-independent files from the host bin directory:
    #   - ELF files are host binaries that cannot run on the target; msi and
    #     iocLogServer are built for the target separately, see do_configure
    #   - files already installed by the target pass are left alone, they carry
    #     target-architecture paths (caRepeater.service)
    install -d ${install_dir}/bin/${EPICS_TARGET_ARCH}
    for tool in ${S}/bin/${EPICS_HOST_ARCH}/*; do
        if [ ! -f "${tool}" ]; then continue; fi
        name=$(basename "${tool}")
        if [ -e "${install_dir}/bin/${EPICS_TARGET_ARCH}/${name}" ]; then continue; fi
        if head -c 4 "${tool}" | grep -q "ELF"; then continue; fi
        install -m 0755 "${tool}" ${install_dir}/bin/${EPICS_TARGET_ARCH}/
        # Some helper scripts embed the host bin directory (S99caRepeater,
        # S99logServer); point them at the target architecture.
        sed -i "s|${EPICS_HOST_ARCH}|${EPICS_TARGET_ARCH}|g" \
            ${install_dir}/bin/${EPICS_TARGET_ARCH}/${name}
    done

    # EPICS 7.0.10 has one script with /bin/env while target images normally
    # provide /usr/bin/perl. Use the target Perl path directly.
    sed -i \
        -e '1s|^#! */bin/env perl$|#!/usr/bin/perl|' \
        -e '1s|^#! */usr/bin/env perl$|#!/usr/bin/perl|' \
        ${install_dir}/bin/${EPICS_TARGET_ARCH}/*.pl

    epics_scrub_build_paths ${install_dir}
    epics_install_symlink

    install -d ${D}${sysconfdir}/profile.d
    # Quoted heredoc delimiter: BitBake expands the recipe variables
    # (${EPICS_PREFIX}, ${PV}, ...) while the runtime shell expands the
    # unbraced $PATH / $LD_LIBRARY_PATH references on the target. Braced
    # ${PATH} must not appear here: BitBake would expand it to the build
    # host PATH and bake TMPDIR paths into the target file.
    cat > ${D}${sysconfdir}/profile.d/epics.sh <<'EOF'
export EPICS_PREFIX=${EPICS_PREFIX}
export EPICS_BASE=${EPICS_PREFIX}/base
export EPICS_BASE_VERSION=${EPICS_PREFIX}/base-${PV}
export EPICS_BASE_BIN=$EPICS_BASE/bin/${EPICS_TARGET_ARCH}
export EPICS_BASE_LIB=$EPICS_BASE/lib/${EPICS_TARGET_ARCH}
export EPICS_TARGET_ARCH=${EPICS_TARGET_ARCH}
export EPICS_HOST_ARCH=${EPICS_TARGET_ARCH}
export PATH=$EPICS_BASE_BIN:$PATH
export LD_LIBRARY_PATH=$EPICS_BASE_LIB:$LD_LIBRARY_PATH
export PERL5LIB=$EPICS_BASE/lib/perl:$PERL5LIB
EOF
}

FILES:${PN} += "${sysconfdir}/profile.d/epics.sh"

# Dependent module recipes run the host-architecture Base tools
# (EPICS_BASE_HOST_BIN, exposed as TOOLS) while generating headers and version
# files, so those tools must be present in their sysroot. They are copied into
# the sysroot after the standard preprocessing, which keeps them out of every
# package and prevents the target strip/objcopy from being applied to
# host-architecture binaries.
epics_stage_host_tools() {
    # Stage into both the versioned directory and the version-independent
    # symlink: sysroot_stage_all dereferences ${EPICS_PREFIX}/base into a real
    # directory before this function runs, so the files added here would
    # otherwise only reach base-${EPICS_MODULE_VERSION}. Dependent module
    # recipes resolve Base through the symlink path, so it needs them too.
    for dir in \
        ${SYSROOT_DESTDIR}${EPICS_INSTALL_BASE}/${EPICS_MODULE_NAME}-${EPICS_MODULE_VERSION} \
        ${SYSROOT_DESTDIR}${EPICS_INSTALL_BASE}/${EPICS_MODULE_NAME}; do
        install -d ${dir}/bin/${EPICS_HOST_ARCH}
        cp -R --no-preserve=ownership ${S}/bin/${EPICS_HOST_ARCH}/. \
            ${dir}/bin/${EPICS_HOST_ARCH}/
        if [ -d ${S}/lib/${EPICS_HOST_ARCH} ]; then
            install -d ${dir}/lib/${EPICS_HOST_ARCH}
            cp -R --no-preserve=ownership ${S}/lib/${EPICS_HOST_ARCH}/. \
                ${dir}/lib/${EPICS_HOST_ARCH}/
        fi
    done
}
SYSROOT_PREPROCESS_FUNCS:append = " epics_stage_host_tools"
