SUMMARY = "EPICS Base"
DESCRIPTION = "Experimental Physics and Industrial Control System Base"
HOMEPAGE = "https://epics-controls.org/"

# EPICS Base uses its own permissive license.
LICENSE = "EPICS"
LIC_FILES_CHKSUM = "file://LICENSE;md5=2eeea17a15fc6ba8501fdcec09b854dc"

PV = "7.0.10"

SRC_URI = "git://github.com/epics-base/epics-base.git;protocol=https;branch=7.0"
SRCREV = "bf11a0c31c919ba85ba2e23b72bcf0b5f9f62e77"
S = "${WORKDIR}/git"

DEPENDS = "perl-native readline ncurses"

# EPICS uses a host build to generate tools and a target build for the IOC
# libraries. PetaLinux supplies the target compiler and sysroot through BitBake.
EPICS_HOST_ARCH = "linux-x86_64"
EPICS_PREFIX ?= "/opt/epics"

EPICS_TARGET_ARCH ?= "${@oe.utils.conditional('TARGET_ARCH', 'aarch64', 'linux-aarch64', 'linux-arm', d)}"

# Common PetaLinux machine names. A project-specific value in local.conf or
# machine configuration takes precedence over these defaults.
EPICS_TARGET_ARCH:zynq = "linux-arm"
EPICS_TARGET_ARCH:zynq7 = "linux-arm"
EPICS_TARGET_ARCH:zynqmp = "linux-aarch64"

# Stage only EPICS Base into the sysroot for future EPICS module recipes.
# Staging the whole prefix would also export unrelated files if a user sets
# EPICS_PREFIX to a broad directory such as /usr.
SYSROOT_DIRS += "${EPICS_PREFIX}/base-${PV} ${EPICS_PREFIX}/base"

# EPICS target-side utilities include Perl scripts.
RDEPENDS:${PN} += "perl"

# EPICS Base makefiles are not fully safe to parallelize on every release.
# Re-enable after the first successful PetaLinux build if desired.
PARALLEL_MAKE = ""

do_configure() {
    install -d ${S}/configure

    cat > ${S}/configure/CONFIG_SITE <<EOF
# Generated by BitBake for PetaLinux.
CROSS_COMPILER_TARGET_ARCHS = ${EPICS_TARGET_ARCH}
EPICS_HOST_ARCH = ${EPICS_HOST_ARCH}
INSTALL_LOCATION = ${S}
FINAL_LOCATION = ${EPICS_PREFIX}/base-${PV}
EOF

    # EPICS 7.0.10 ships a target-specific CONFIG_SITE for
    # linux-x86_64/linux-aarch64 that points at an old Xilinx SDK path. Replace
    # it with the target tools selected by BitBake. Keep these assignments in
    # the target-specific file; host tools must continue using the build host.
    cat > ${S}/configure/os/CONFIG_SITE.${EPICS_HOST_ARCH}.${EPICS_TARGET_ARCH} <<EOF
# Generated by BitBake for PetaLinux.
CC = $(echo "${CC}" | cut -d ' ' -f 1)
CXX = $(echo "${CXX}" | cut -d ' ' -f 1)
CCC = $(echo "${CXX}" | cut -d ' ' -f 1)
LD = $(echo "${LD}" | cut -d ' ' -f 1) -r
AR = ${AR} -rc
RANLIB = ${RANLIB}
STATIC_BUILD = YES
SHARED_LIBRARIES = NO
EOF
}

do_compile() {
    # Build host tools first. EPICS target builds use these tools while
    # generating databases and headers.
    # EPICS runs host tools such as msi during both host and target builds.
    # Their host libraries are installed below ${S}, so expose that directory
    # only for this build task.
    export LD_LIBRARY_PATH="${S}/lib/${EPICS_HOST_ARCH}:${RECIPE_SYSROOT_NATIVE}/usr/lib:${LD_LIBRARY_PATH}"

    oe_runmake -C ${S} install.${EPICS_HOST_ARCH} \
        EPICS_HOST_ARCH="${EPICS_HOST_ARCH}" \
        CROSS_COMPILER_TARGET_ARCHS="${EPICS_TARGET_ARCH}" \
        USR_CFLAGS="${BUILD_CFLAGS}" \
        USR_CXXFLAGS="${BUILD_CXXFLAGS}" \
        USR_LDFLAGS="${BUILD_LDFLAGS}"

    # Build and install target libraries and executables with the BitBake
    # cross compiler. Do not pass CMPLR_PREFIX globally: that would make the
    # host build invoke the target compiler.
    oe_runmake -C ${S} install.${EPICS_TARGET_ARCH} \
        EPICS_HOST_ARCH="${EPICS_HOST_ARCH}" \
        CROSS_COMPILER_TARGET_ARCHS="${EPICS_TARGET_ARCH}" \
        USR_CFLAGS="$(echo "${CC}" | cut -d ' ' -f 2-) ${CFLAGS}" \
        USR_CXXFLAGS="$(echo "${CXX}" | cut -d ' ' -f 2-) ${CXXFLAGS}" \
        USR_LDFLAGS="$(echo "${LD}" | cut -d ' ' -f 2-) ${LDFLAGS}"
}

do_install() {
    install_dir=${D}${EPICS_PREFIX}/base-${PV}
    install -d ${install_dir}

    # Copy common EPICS files from the compile install tree.
    for subdir in cfg configure db dbd doc html include templates; do
        if [ -d ${S}/${subdir} ]; then
            install -d ${install_dir}/${subdir}
            cp -R --no-preserve=ownership ${S}/${subdir}/. ${install_dir}/${subdir}/
        fi
    done

    # Keep architecture-independent Perl modules only. The build can place
    # host-native XS modules such as libCap5.so under lib/perl; those are not
    # usable on the target and must not enter the package.
    if [ -d ${S}/lib/perl ]; then
        find ${S}/lib/perl -type f \( -name '*.pm' -o -name '*.pl' \) -print | \
            while read -r module; do
                relative=${module#${S}/lib/perl/}
                install -D -m 0644 "${module}" \
                    "${install_dir}/lib/perl/${relative}"
            done
    fi

    # Ship target binaries and libraries only. Host binaries/libraries remain
    # available in ${S} for build-time tools but never enter ${D}.
    for subdir in bin lib; do
        if [ -d ${S}/${subdir}/${EPICS_TARGET_ARCH} ]; then
            install -d ${install_dir}/${subdir}/${EPICS_TARGET_ARCH}
            cp -R --no-preserve=ownership ${S}/${subdir}/${EPICS_TARGET_ARCH}/. \
                ${install_dir}/${subdir}/${EPICS_TARGET_ARCH}/
        fi
    done

    # EPICS 7.0.10 keeps architecture-independent scripts in src/tools. A
    # cross build does not guarantee that they are copied to bin/<host-arch>,
    # so do not make packaging depend on that build-side layout.
    install -d ${install_dir}/bin/${EPICS_TARGET_ARCH}
    for script in ${S}/src/tools/*.pl ${S}/src/tools/*.py; do
        [ -f "${script}" ] || continue
        install -m 0755 "${script}" ${install_dir}/bin/${EPICS_TARGET_ARCH}/
    done

    # EPICS 7.0.10 has one script with /bin/env while target images normally
    # provide /usr/bin/perl. Use the target Perl path directly.
    sed -i \
        -e '1s|^#! */bin/env perl$|#!/usr/bin/perl|' \
        -e '1s|^#! */usr/bin/env perl$|#!/usr/bin/perl|' \
        ${install_dir}/bin/${EPICS_TARGET_ARCH}/*.pl

    # Do not publish the temporary source path in text configuration files.
    grep -Ilr "${S}" ${install_dir} | \
        xargs -r sed -i "s|${S}|${EPICS_PREFIX}/base-${PV}|g"

    install -d ${D}${EPICS_PREFIX}
    ln -sfn base-${PV} ${D}${EPICS_PREFIX}/base

    install -d ${D}${sysconfdir}/profile.d
    cat > ${D}${sysconfdir}/profile.d/epics.sh <<EOF
export EPICS_PREFIX=${EPICS_PREFIX}
export EPICS_BASE=${EPICS_PREFIX}/base
export EPICS_BASE_VERSION=${EPICS_PREFIX}/base-${PV}
export EPICS_BASE_BIN=\${EPICS_BASE}/bin/${EPICS_TARGET_ARCH}
export EPICS_BASE_LIB=\${EPICS_BASE}/lib/${EPICS_TARGET_ARCH}
export EPICS_TARGET_ARCH=${EPICS_TARGET_ARCH}
export EPICS_HOST_ARCH=${EPICS_TARGET_ARCH}
export PATH=\${EPICS_BASE_BIN}:\${PATH}
export LD_LIBRARY_PATH=\${EPICS_BASE_LIB}:\${LD_LIBRARY_PATH}
export PERL5LIB=\${EPICS_BASE}/lib/perl:\${PERL5LIB}
EOF
}

FILES:${PN} += " \
    ${EPICS_PREFIX}/base-${PV} \
    ${EPICS_PREFIX}/base \
    ${sysconfdir}/profile.d/epics.sh \
"

FILES:${PN}-staticdev += " \
    ${EPICS_PREFIX}/base-${PV}/lib/${EPICS_TARGET_ARCH}/*.a \
"
