BBPATH .= ":${LAYERDIR}"

BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "epics"
BBFILE_PATTERN_epics = "^${LAYERDIR}/"
BBFILE_PRIORITY_epics = "6"

# Keep this list aligned with the Yocto release used by the PetaLinux project.
LAYERSERIES_COMPAT_epics = "scarthgap wrynose"
LAYERDEPENDS_epics = "core"
