# Run an EPICS IOC under procServ, supervised by systemd, with a per-instance
# port allocation.
#
# A single-instance IOC ships <PN>.service. A multi-instance IOC ships the
# systemd template <PN>@.service: `systemctl enable --now '<PN>@ioc1'` starts one
# IOC, and the instance env file /etc/epics/<PN>/ioc1.env selects its ports, PV
# prefix and state directory. See docs/port-allocation.md.

inherit epics-ioc

# procServ is exec'd at run time only; nothing is linked against it.
RDEPENDS:${PN} += "procserv"

# --- port allocation -------------------------------------------------------

EPICS_IOC_PORT_BASE  ?= "21000"
IOC_PORT_BLOCK_INDEX ?= "0"
IOC_PORT_BLOCK       ?= "${@int(d.getVar('EPICS_IOC_PORT_BASE')) + 100 * int(d.getVar('IOC_PORT_BLOCK_INDEX'))}"

python() {
    base = int(d.getVar("EPICS_IOC_PORT_BASE"))
    block = int(d.getVar("IOC_PORT_BLOCK"))
    if block < base or block >= base + 1000:
        bb.warn("%s: IOC_PORT_BLOCK %d is outside the site range %d-%d"
                % (d.getVar("PN"), block, base, base + 999))
    elif (block - base) % 100:
        bb.warn("%s: IOC_PORT_BLOCK %d is not 100-aligned from EPICS_IOC_PORT_BASE"
                % (d.getVar("PN"), block))
}

# --- procServ / IOC --------------------------------------------------------

# -A lets the console be reached from other hosts (compile-time support comes
# from the procserv recipe's "remote" PACKAGECONFIG).
PROCSERV_ARGS ?= "-A"

# Name of the executable under bin/<target-arch>/. Empty to execute the st.cmd
# directly through its shebang.
IOC_APP_NAME ?= ""
# Directory below the install root that holds st.cmd, e.g. iocBoot/iocdemo.
IOC_PATH ?= ""
IOC_ST_CMD ?= "st.cmd"

# Shell statement run after the ports are resolved and before procServ starts.
# Functions it calls can be defined by a sibling <IOC_PATH>/ioc-start.pre.
EPICS_IOC_START_PRE ?= ""

EPICS_IOC_MULTI_INSTANCE ?= "0"
EPICS_IOC_ENV_DIR ?= "${sysconfdir}/epics/${PN}"
# Additional instance env files to install, as source paths.
EPICS_IOC_INSTANCE_ENVS ?= ""

inherit systemd

# The operator enables an IOC explicitly; installing it must not start it.
SYSTEMD_AUTO_ENABLE:${PN} = "disable"

SYSTEMD_SERVICE:${PN} = "${PN}${@bb.utils.contains('EPICS_IOC_MULTI_INSTANCE', '1', '@.service', '.service', d)}"

do_install:append() {
    install_dir=${D}${EPICS_INSTALL_BASE}/${EPICS_MODULE_NAME}-${EPICS_MODULE_VERSION}
    unit_dir=${D}${systemd_system_unitdir}
    env_dir=${D}${EPICS_IOC_ENV_DIR}

    install -d ${unit_dir} ${env_dir}

    # The generated scripts use quoted heredocs: BitBake expands ${...} (its own
    # variables) while $var and $((...)) are left for the target shell. Only
    # *.env values are referenced with shell syntax.
    #
    # Keep the closing brace of any shell function in these heredocs indented:
    # BitBake's parser ends the surrounding do_install body on a line that is
    # exactly "}", so a column-zero brace inside the text would truncate it.

    cat > ${install_dir}/ioc-ports.sh <<'IOCPORTSEOF'
#!/bin/sh
# Generated by epics-ioc-systemd.bbclass -- do not edit.
# Per-instance port allocation for ${PN}.

IOC_PORT_BLOCK="${IOC_PORT_BLOCK}"
IOC_PORT_STRIDE=10
IOC_INSTANCE_MAX=9
IOC_ENV_DIR="${EPICS_IOC_ENV_DIR}"

# Resolve the ports for $IOC_INSTANCE_INDEX. Values already set by the instance
# env file are kept, so a single port can be pinned explicitly.
ioc_ports_resolve() {
    [ -n "$IOC_INSTANCE_INDEX" ] || IOC_INSTANCE_INDEX=0
    _base=$(( IOC_PORT_BLOCK + IOC_INSTANCE_INDEX * IOC_PORT_STRIDE ))
    [ -n "$PS_PORT" ] || PS_PORT=$_base
    [ -n "$APP_PORT_1" ] || APP_PORT_1=$(( _base + 1 ))
    [ -n "$APP_PORT_2" ] || APP_PORT_2=$(( _base + 2 ))
    export IOC_INSTANCE_INDEX PS_PORT APP_PORT_1 APP_PORT_2
    }

ioc_ports_show() {
    # Always resolve: a preset PS_PORT alone must not leave the app ports empty.
    ioc_ports_resolve
    echo "ioc=${PN} instance=$IOC_INSTANCE_INDEX block=$IOC_PORT_BLOCK"
    echo "PS_PORT=$PS_PORT APP_PORT_1=$APP_PORT_1 APP_PORT_2=$APP_PORT_2"
    }

_ioc_ports_used_indexes() {
    for _f in "$IOC_ENV_DIR"/*.env; do
        [ -e "$_f" ] || continue
        sed -n 's/^[[:space:]]*IOC_INSTANCE_INDEX=\([0-9][0-9]*\).*/\1/p' "$_f" | tail -n 1
    done
    }

ioc_ports_next() {
    _used=" $(_ioc_ports_used_indexes | tr '\n' ' ') "
    _n=0
    while [ "$_n" -le "$IOC_INSTANCE_MAX" ]; do
        case "$_used" in
            *" $_n "*) ;;
            *) echo "$_n"; return 0 ;;
        esac
        _n=$(( _n + 1 ))
    done
    echo "no free instance index (max $IOC_INSTANCE_MAX)" >&2
    return 1
    }

ioc_ports_audit() {
    _rc=0
    _seen=" "
    for _idx in $(_ioc_ports_used_indexes); do
        case "$_seen" in
            *" $_idx "*)
                echo "collision: IOC_INSTANCE_INDEX=$_idx used twice in $IOC_ENV_DIR -> PS_PORT=$(( IOC_PORT_BLOCK + _idx * IOC_PORT_STRIDE ))" >&2
                _rc=1 ;;
        esac
        _seen="$_seen$_idx "
    done
    [ "$_rc" = 0 ] && echo "ok: no instance-index collisions in $IOC_ENV_DIR"
    return $_rc
    }

_ioc_ports_dispatch() {
    case "$1" in
        --show)  ioc_ports_show ;;
        --next)  ioc_ports_next ;;
        --audit) ioc_ports_audit ;;
        *) echo "usage: $0 [--show|--next|--audit]" >&2; return 2 ;;
    esac
    }
# Act only when executed, not when sourced by ioc-start.sh.
[ "$(basename "$0")" = "ioc-ports.sh" ] && _ioc_ports_dispatch "$@"
IOCPORTSEOF

    cat > ${install_dir}/ioc-start.sh <<'IOCSTARTEOF'
#!/bin/sh
# Generated by epics-ioc-systemd.bbclass -- do not edit.
set -e

HERE="$(cd "$(dirname "$0")" && pwd)"
INSTANCE="$1"
[ -n "$INSTANCE" ] || INSTANCE=default

# Instance configuration: IOC_INSTANCE_INDEX, IOC_PREFIX, IOC_STATE, ...
[ -r "${EPICS_IOC_ENV_DIR}/$INSTANCE.env" ] && . "${EPICS_IOC_ENV_DIR}/$INSTANCE.env"

. "$HERE/ioc-ports.sh"
ioc_ports_resolve

[ -n "$IOC_PREFIX" ] || IOC_PREFIX="$INSTANCE:"
[ -n "$IOC_STATE" ] || IOC_STATE="/var/lib/${PN}/$INSTANCE"
[ -n "$PROCSERV_ARGS" ] || PROCSERV_ARGS="-A"
export IOC_PREFIX IOC_STATE

mkdir -p "$IOC_STATE"
cd "$HERE/${IOC_PATH}"

# Optional hook, e.g. an external device simulator bound to $APP_PORT_1. It runs
# as a sibling process in this service's cgroup, so systemd stops it with the
# IOC.
[ -r "$HERE/${IOC_PATH}/ioc-start.pre" ] && . "$HERE/${IOC_PATH}/ioc-start.pre"

${EPICS_IOC_START_PRE}

exec procServ -f -L - -P "$PS_PORT" $PROCSERV_ARGS @IOC_EXEC@
IOCSTARTEOF

    # Point procServ at either the IOC executable or the st.cmd directly. The
    # placeholder keeps the shell metacharacters out of the BitBake heredoc.
    if [ -n "${IOC_APP_NAME}" ]; then
        ioc_exec="\"\$HERE/bin/${EPICS_TARGET_ARCH}/${IOC_APP_NAME}\" ${IOC_ST_CMD}"
    else
        ioc_exec="./${IOC_ST_CMD}"
    fi
    sed -i "s,@IOC_EXEC@,${ioc_exec}," ${install_dir}/ioc-start.sh

    # An st.cmd executed directly through its shebang must be executable.
    [ -f "${install_dir}/${IOC_PATH}/${IOC_ST_CMD}" ] && \
        chmod 0755 ${install_dir}/${IOC_PATH}/${IOC_ST_CMD}

    chmod 0755 ${install_dir}/ioc-ports.sh ${install_dir}/ioc-start.sh

    cat > ${install_dir}/ioc-instance-add <<'IOCADDEOF'
#!/bin/sh
# Generated by epics-ioc-systemd.bbclass -- do not edit.
# Create an instance env file with the next free IOC_INSTANCE_INDEX.
set -e

[ -n "$1" ] || { echo "usage: $0 <instance-name>" >&2; exit 2; }

HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/ioc-ports.sh"

_name="$1"
_target="${EPICS_IOC_ENV_DIR}/$_name.env"
[ -e "$_target" ] && { echo "$_target already exists" >&2; exit 1; }

_index="$(ioc_ports_next)"
cat > "$_target" <<EOF
IOC_INSTANCE_INDEX=$_index
IOC_PREFIX=$_name:
IOC_STATE=/var/lib/${PN}/$_name
EOF
echo "created $_target (IOC_INSTANCE_INDEX=$_index)"
IOCADDEOF
    chmod 0755 ${install_dir}/ioc-instance-add

    # Instance env template.
    cat > ${env_dir}/example.env <<EOF
# Per-instance configuration for ${PN}. Copy to <name>.env, adjust, then
#   systemctl enable --now '${PN}@<name>'
# IOC_INSTANCE_INDEX must be unique per IOC type; it selects a 10-port stride
# out of this IOC's block starting at ${IOC_PORT_BLOCK}. See
# docs/port-allocation.md.
IOC_INSTANCE_INDEX=0
IOC_PREFIX=example:
IOC_STATE=/var/lib/${PN}/example

# PS_PORT=...       # override the procServ console port
# APP_PORT_1=...    # override the primary application port
# APP_PORT_2=...    # override the secondary application port
EOF

    for instance in ${EPICS_IOC_INSTANCE_ENVS}; do
        install -m 0644 "$instance" "${env_dir}/$(basename "$instance")"
    done

    if [ "${EPICS_IOC_MULTI_INSTANCE}" = "1" ]; then
        cat > ${unit_dir}/${PN}@.service <<EOF
[Unit]
Description=%p IOC instance %i
After=network.target

[Service]
Type=simple
EnvironmentFile=-${EPICS_IOC_ENV_DIR}/%i.env
ExecStart=${EPICS_INSTALL_BASE}/${EPICS_MODULE_NAME}/ioc-start.sh %i
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
EOF
    else
        cat > ${unit_dir}/${PN}.service <<EOF
[Unit]
Description=${PN} IOC
After=network.target

[Service]
Type=simple
ExecStart=${EPICS_INSTALL_BASE}/${EPICS_MODULE_NAME}/ioc-start.sh
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
EOF
    fi
}

FILES:${PN} += "${EPICS_IOC_ENV_DIR}"
