# Common EPICS build machinery for cross-built EPICS modules.
#
# EPICS Base uses this class as well: it sets EPICS_MODULE_NAME="base",
# EPICS_WRITE_RELEASE="0", EPICS_HOST_PASS="1" and overrides do_configure /
# do_install for its own layout (filtered bin/lib, Perl modules, profile.d).
#
# Modules inherit the class and normally only provide the usual recipe
# metadata plus EPICS_RELEASE_EXTRA for their own EPICS dependencies.

EPICS_PREFIX ?= "/opt/epics"

# Install root for support modules. EPICS Base overrides this to
# ${EPICS_PREFIX} so Base stays at /opt/epics/base[-<ver>]; every other
# module installs under /opt/epics/modules/<name>[-<ver>].
EPICS_INSTALL_BASE ?= "${EPICS_PREFIX}/modules"

EPICS_HOST_ARCH ?= "linux-x86_64"

# Map the BitBake target architecture onto the EPICS target architecture name.
# aarch64 is the default (PetaLinux ARM64 targets); x86_64 supports native-arch
# builds; 32-bit ARM maps to linux-arm.
def epics_target_arch(d):
    mapping = {
        "aarch64": "linux-aarch64",
        "x86_64":  "linux-x86_64",
        "arm":     "linux-arm",
    }
    return mapping.get(d.getVar("TARGET_ARCH"), "linux-aarch64")

EPICS_TARGET_ARCH ??= "${@epics_target_arch(d)}"

# Installed directory below ${EPICS_INSTALL_BASE}. A version-independent
# symlink ${EPICS_INSTALL_BASE}/${EPICS_MODULE_NAME} is created so downstream
# modules can reference a staged dependency without tracking its version.
EPICS_MODULE_NAME ??= "${BPN}"
EPICS_MODULE_VERSION ??= "${PV}"

# File receiving the generated target toolchain settings. EPICS reads
# configure/CONFIG_SITE.$(EPICS_HOST_ARCH).$(T_A) after the settings inherited
# from EPICS Base, so a module-local file takes precedence. EPICS Base itself
# reads configure/os/CONFIG_SITE.$(EPICS_HOST_ARCH).$(T_A) from its own tree.
EPICS_CONFIG_SITE_FILE ??= "configure/CONFIG_SITE.${EPICS_HOST_ARCH}.${EPICS_TARGET_ARCH}"

# Subdirectories copied verbatim into the target installation. Recipes that
# must filter architecture-specific subdirectories (EPICS Base) trim this list
# and install those parts themselves.
EPICS_INSTALL_SUBDIRS ??= "bin lib db dbd include cfg templates html doc"

# Extra configure/RELEASE lines for this module's EPICS dependencies, e.g.
#   EPICS_RELEASE_EXTRA = "ASYN = ${RECIPE_SYSROOT}${EPICS_PREFIX}/modules/asyn"
EPICS_RELEASE_EXTRA ??= ""

# Build-time dependency on EPICS Base; empty when the recipe is Base itself.
EPICS_DEPENDS_BASE ??= "epics-base"

# Runtime dependencies; shlibs scanning does not cover ${EPICS_PREFIX}, so they
# must be declared explicitly.
EPICS_RDEPENDS ??= "epics-base"

# Generate configure/RELEASE with EPICS_BASE. EPICS Base has no
# configure/RELEASE: set to 0 there.
EPICS_WRITE_RELEASE ??= "1"

# Build and install the host-architecture pass before the target pass. Modules
# normally do not build host tools (they use the staged Base tools); modules
# that ship a host tool (for example SNCSEQ's snc) set this to 1.
EPICS_HOST_PASS ??= "0"

# CHECK_RELEASE compares the values each dependency recorded in its own
# configure/RELEASE against the ones used by the current module. Staged modules
# carry the sysroot path of their own build, which never matches the consumer's
# sysroot, so the check would always report false mismatches.
EPICS_CHECK_RELEASE ??= "NO"

inherit perlnative

DEPENDS += "${EPICS_DEPENDS_BASE}"
RDEPENDS:${PN} += "${EPICS_RDEPENDS}"

# Stage this module for future EPICS module recipes. Staging the whole
# ${EPICS_PREFIX} would also export unrelated files if a user sets
# EPICS_PREFIX to a broad directory such as /usr.
SYSROOT_DIRS += " \
    ${EPICS_INSTALL_BASE}/${EPICS_MODULE_NAME}-${EPICS_MODULE_VERSION} \
    ${EPICS_INSTALL_BASE}/${EPICS_MODULE_NAME} \
"

FILES:${PN} += " \
    ${EPICS_INSTALL_BASE}/${EPICS_MODULE_NAME}-${EPICS_MODULE_VERSION} \
    ${EPICS_INSTALL_BASE}/${EPICS_MODULE_NAME} \
"

# Everything ships in ${PN} (single-package layout, kept intentionally so the
# target can be used for development). The versioned .so symlinks therefore
# live in the runtime package, which dev-so QA would otherwise reject.
INSANE_SKIP:${PN} += "dev-so"

FILES:${PN}-staticdev += " \
    ${EPICS_INSTALL_BASE}/${EPICS_MODULE_NAME}-${EPICS_MODULE_VERSION}/lib/${EPICS_TARGET_ARCH}/*.a \
"

# Write the target toolchain settings. The full BitBake compiler commands are
# passed verbatim: they may consist of several words (ccache, --sysroot=...)
# and GNU make executes them as-is, so no string splitting is needed and ccache
# stays supported. LD keeps the upstream "-r" default (relocatable object
# merging); final linking goes through CCC/CXX.
epics_generate_config_site() {
    install -d "$(dirname ${S}/${EPICS_CONFIG_SITE_FILE})"
    cat > ${S}/${EPICS_CONFIG_SITE_FILE} <<EOF
# Generated by BitBake for PetaLinux.
CHECK_RELEASE = ${EPICS_CHECK_RELEASE}
CC = ${CC}
CXX = ${CXX}
CCC = ${CXX}
LD = ${TARGET_PREFIX}ld -r
AR = ${AR} -rc
RANLIB = ${RANLIB}
# Cross sysroot. Some modules (e.g. asyn >= 4.46) build include paths from
# $(SYSROOT) but EPICS Base does not define it.
SYSROOT = ${RECIPE_SYSROOT}
EOF
}

# Point configure/RELEASE at the staged EPICS dependencies. Appended so it wins
# over earlier definitions in the file.
epics_generate_release() {
    install -d ${S}/configure
    cat >> ${S}/configure/RELEASE <<EOF

# Generated by BitBake: staged locations inside the recipe sysroot.
EPICS_BASE = ${RECIPE_SYSROOT}${EPICS_PREFIX}/base
${EPICS_RELEASE_EXTRA}
EOF
}

epics_install_subdirs() {
    install_dir="$1"
    for subdir in ${EPICS_INSTALL_SUBDIRS}; do
        [ -d ${S}/${subdir} ] || continue
        install -d ${install_dir}/${subdir}
        cp -R --no-preserve=ownership ${S}/${subdir}/. ${install_dir}/${subdir}/
    done
}

# Installed text files must not publish the temporary source path or the build
# TMPDIR (the latter also trips the buildpaths QA check). Only comment lines are
# dropped: those are C preprocessor line markers, never functional settings.
epics_scrub_build_paths() {
    install_dir="$1"
    grep -Ilr "${S}" ${install_dir} | \
        xargs -r sed -i "s|${S}|${EPICS_INSTALL_BASE}/${EPICS_MODULE_NAME}-${EPICS_MODULE_VERSION}|g"
    grep -Ilr "${TMPDIR}" ${install_dir} | \
        xargs -r sed -i "\|^#.*${TMPDIR}|d"
}

epics_install_symlink() {
    install -d ${D}${EPICS_INSTALL_BASE}
    ln -sfn ${EPICS_MODULE_NAME}-${EPICS_MODULE_VERSION} \
        ${D}${EPICS_INSTALL_BASE}/${EPICS_MODULE_NAME}
}

do_configure() {
    install -d ${S}/configure
    epics_generate_config_site
    if [ "${EPICS_WRITE_RELEASE}" = "1" ]; then
        epics_generate_release
    fi
}

do_compile() {
    # Host tools run during the build need the staged Base host libraries and
    # the host tools built in this tree, so expose those directories only for
    # this task.
    export LD_LIBRARY_PATH="${RECIPE_SYSROOT}${EPICS_PREFIX}/base/lib/${EPICS_HOST_ARCH}:${S}/lib/${EPICS_HOST_ARCH}:${RECIPE_SYSROOT_NATIVE}/usr/lib:${LD_LIBRARY_PATH}"

    if [ "${EPICS_HOST_PASS}" = "1" ]; then
        oe_runmake -C ${S} install.${EPICS_HOST_ARCH} \
            EPICS_HOST_ARCH="${EPICS_HOST_ARCH}" \
            CROSS_COMPILER_TARGET_ARCHS="${EPICS_TARGET_ARCH}" \
            USR_CFLAGS="${BUILD_CFLAGS}" \
            USR_CXXFLAGS="${BUILD_CXXFLAGS}" \
            USR_LDFLAGS="${BUILD_LDFLAGS}"
    fi

    # Build and install target libraries and executables with the BitBake cross
    # compiler. The compiler commands (including --sysroot) come from the
    # generated CONFIG_SITE file; only the flag sets are passed here.
    if [ "${EPICS_TARGET_ARCH}" != "${EPICS_HOST_ARCH}" ]; then
        oe_runmake -C ${S} install.${EPICS_TARGET_ARCH} \
            EPICS_HOST_ARCH="${EPICS_HOST_ARCH}" \
            CROSS_COMPILER_TARGET_ARCHS="${EPICS_TARGET_ARCH}" \
            USR_CFLAGS="${CFLAGS}" \
            USR_CXXFLAGS="${CXXFLAGS}" \
            USR_LDFLAGS="${LDFLAGS}"
    fi
}

do_install() {
    install_dir=${D}${EPICS_INSTALL_BASE}/${EPICS_MODULE_NAME}-${EPICS_MODULE_VERSION}
    install -d ${install_dir}

    epics_install_subdirs ${install_dir}

    # A cross build installs both a host and a target bin/lib tree. Only the
    # target architecture belongs in the package: the target strip/objcopy
    # cannot process host binaries and they must not run on the target.
    if [ "${EPICS_HOST_ARCH}" != "${EPICS_TARGET_ARCH}" ]; then
        rm -rf ${install_dir}/bin/${EPICS_HOST_ARCH} \
               ${install_dir}/lib/${EPICS_HOST_ARCH}
    fi

    epics_scrub_build_paths ${install_dir}
    epics_install_symlink
}
