# Run an EPICS IOC under procServ, supervised by systemd, with per-instance
# console ports.
#
# A single-instance IOC ships <PN>.service. A multi-instance IOC ships the
# systemd template <PN>@.service: `systemctl enable --now '<PN>@ioc1'` starts one
# IOC, and the instance env file /etc/epics/<PN>/ioc1.env selects its console
# port, PV prefix and state directory. See docs/port-allocation.md.
#
# Port management is layered. The procServ console has no discovery mechanism,
# so it is the one port that is statically allocated: a global slot index
# (IOC_INSTANCE_INDEX, shared by every IOC on the target) picks a 10-port stride
# out of the site range, and the console sits at its first port. The CA and PVA
# service ports are not managed here at all: EPICS natively gives the first IOC
# the default ports and lets every further one fall back to a dynamic port that
# beacons advertise. An instance that must be reachable on a fixed port pins
# CA_PORT/PVA_PORT in its env file.

inherit epics-ioc

# procServ is exec'd at run time only; nothing is linked against it.
RDEPENDS:${PN} += "procserv"

# --- console ports ---------------------------------------------------------

EPICS_IOC_PORT_BASE ?= "21000"
# Instance env files live here; the audit and --next helpers scan every IOC's
# directory below it, because a console-port collision is possible across
# different IOCs, not only within one.
EPICS_IOC_ENV_ROOT ?= "${sysconfdir}/epics"
# procServ -I writes the running server's PID and endpoints here (tmpfs).
EPICS_IOC_RUN_DIR ?= "/run/epics/${PN}"

# --- procServ / IOC --------------------------------------------------------

# -A lets the console be reached from other hosts (compile-time support comes
# from the procserv recipe's "remote" PACKAGECONFIG).
PROCSERV_ARGS ?= "-A"

# Name of the executable under bin/<target-arch>/. Empty to execute the st.cmd
# directly through its shebang.
IOC_APP_NAME ?= ""
# Directory below the install root that holds st.cmd, e.g.
# iocBoot/ioctestAsynPortDriver.
IOC_PATH ?= ""
IOC_ST_CMD ?= "st.cmd"

# Shell statement run after the ports are resolved and before procServ starts.
# Functions it calls can be defined by a sibling <IOC_PATH>/ioc-start.pre.
EPICS_IOC_START_PRE ?= ""

EPICS_IOC_MULTI_INSTANCE ?= "0"
EPICS_IOC_ENV_DIR ?= "${sysconfdir}/epics/${PN}"
# Additional instance env files to install, as source paths.
EPICS_IOC_INSTANCE_ENVS ?= ""

inherit systemd

# The operator enables an IOC explicitly; installing it must not start it.
SYSTEMD_AUTO_ENABLE:${PN} = "disable"

SYSTEMD_SERVICE:${PN} = "${PN}${@bb.utils.contains('EPICS_IOC_MULTI_INSTANCE', '1', '@.service', '.service', d)}"

do_install:append() {
    install_dir=${D}${EPICS_INSTALL_BASE}/${EPICS_MODULE_NAME}-${EPICS_MODULE_VERSION}
    unit_dir=${D}${systemd_system_unitdir}
    env_dir=${D}${EPICS_IOC_ENV_DIR}

    install -d ${unit_dir} ${env_dir}

    # The generated scripts use quoted heredocs: BitBake expands ${...} (its own
    # variables) while $var and $((...)) are left for the target shell. Only
    # *.env values are referenced with shell syntax.
    #
    # Keep the closing brace of any shell function in these heredocs indented:
    # BitBake's parser ends the surrounding do_install body on a line that is
    # exactly "}", so a column-zero brace inside the text would truncate it.

    cat > ${install_dir}/ioc-ports.sh <<'IOCPORTSEOF'
#!/bin/sh
# Generated by epics-ioc-systemd.bbclass -- do not edit.
# Console-port slots for ${PN}, and the helpers around them.

EPICS_IOC_PORT_BASE="${EPICS_IOC_PORT_BASE}"
IOC_PORT_STRIDE=10
IOC_INSTANCE_MAX=99
IOC_ENV_DIR="${EPICS_IOC_ENV_DIR}"
IOC_ENV_ROOT="${EPICS_IOC_ENV_ROOT}"
IOC_RUN_DIR="${EPICS_IOC_RUN_DIR}"

# Resolve the console and application ports for $IOC_INSTANCE_INDEX. Values
# already set by the instance env file are kept, so a port can be pinned.
# CA_PORT/PVA_PORT are deliberately not derived: the EPICS service ports stay
# dynamic unless the instance env pins them.
ioc_ports_resolve() {
    [ -n "$IOC_INSTANCE_INDEX" ] || IOC_INSTANCE_INDEX=0
    _base=$(( EPICS_IOC_PORT_BASE + IOC_INSTANCE_INDEX * IOC_PORT_STRIDE ))
    [ -n "$PS_PORT" ] || PS_PORT=$_base
    [ -n "$APP_PORT_1" ] || APP_PORT_1=$(( _base + 1 ))
    [ -n "$APP_PORT_2" ] || APP_PORT_2=$(( _base + 2 ))
    export IOC_INSTANCE_INDEX PS_PORT APP_PORT_1 APP_PORT_2
    }

ioc_ports_show() {
    # Always resolve: a preset PS_PORT alone must not leave the app ports empty.
    ioc_ports_resolve
    echo "ioc=${PN} instance=$IOC_INSTANCE_INDEX"
    echo "PS_PORT=$PS_PORT APP_PORT_1=$APP_PORT_1 APP_PORT_2=$APP_PORT_2"
    if [ -n "$CA_PORT" ]; then
        echo "EPICS_CA_SERVER_PORT=$CA_PORT (pinned)"
    else
        echo "EPICS_CA_SERVER_PORT=dynamic (first IOC gets 5064)"
    fi
    if [ -n "$PVA_PORT" ]; then
        echo "EPICS_PVAS_SERVER_PORT=$PVA_PORT (pinned)"
    else
        echo "EPICS_PVAS_SERVER_PORT=dynamic (first IOC gets 5075)"
    fi
    if [ -n "$1" ] && [ -r "$IOC_RUN_DIR/$1.info" ]; then
        echo "--- procServ endpoints ($IOC_RUN_DIR/$1.info)"
        cat "$IOC_RUN_DIR/$1.info"
    fi
    }

_ioc_ports_env_files() {
    # Every IOC's instance env files: a console port collides across different
    # IOCs just as it does within one, so the slot index is global.
    for _f in "$IOC_ENV_ROOT"/*/*.env; do
        [ -e "$_f" ] || continue
        echo "$_f"
    done
    }

_ioc_ports_file_index() {
    sed -n 's/^[[:space:]]*IOC_INSTANCE_INDEX=\([0-9][0-9]*\).*/\1/p' "$1" | tail -n 1
    }

ioc_ports_next() {
    _used=" "
    for _f in $(_ioc_ports_env_files); do
        _idx=$(_ioc_ports_file_index "$_f")
        _used="$_used${_idx:-0} "
    done
    _n=0
    while [ "$_n" -le "$IOC_INSTANCE_MAX" ]; do
        case "$_used" in
            *" $_n "*) ;;
            *) echo "$_n"; return 0 ;;
        esac
        _n=$(( _n + 1 ))
    done
    echo "no free instance index (max $IOC_INSTANCE_MAX)" >&2
    return 1
    }

ioc_ports_audit() {
    _rc=0
    _seen=" "
    for _f in $(_ioc_ports_env_files); do
        _idx=$(_ioc_ports_file_index "$_f")
        _idx="${_idx:-0}"
        case "$_seen" in
            *" $_idx "*)
                echo "collision: IOC_INSTANCE_INDEX=$_idx used again by $_f -> PS_PORT=$(( EPICS_IOC_PORT_BASE + _idx * IOC_PORT_STRIDE ))" >&2
                _rc=1 ;;
        esac
        _seen="$_seen$_idx "
    done
    [ "$_rc" = 0 ] && echo "ok: no console-port collisions under $IOC_ENV_ROOT"
    return $_rc
    }

_ioc_ports_dispatch() {
    case "$1" in
        --show)  shift; ioc_ports_show "$@" ;;
        --next)  ioc_ports_next ;;
        --audit) ioc_ports_audit ;;
        *) echo "usage: $0 [--show [instance]|--next|--audit]" >&2; return 2 ;;
    esac
    }
# Act only when executed, not when sourced by ioc-start.sh.
[ "$(basename "$0")" = "ioc-ports.sh" ] && _ioc_ports_dispatch "$@"
IOCPORTSEOF

    cat > ${install_dir}/ioc-start.sh <<'IOCSTARTEOF'
#!/bin/sh
# Generated by epics-ioc-systemd.bbclass -- do not edit.
set -e

HERE="$(cd "$(dirname "$0")" && pwd)"
INSTANCE="$1"
[ -n "$INSTANCE" ] || INSTANCE=default

# Instance configuration: IOC_INSTANCE_INDEX, IOC_PREFIX, IOC_STATE, and the
# optional CA_PORT/PVA_PORT pins.
[ -r "${EPICS_IOC_ENV_DIR}/$INSTANCE.env" ] && . "${EPICS_IOC_ENV_DIR}/$INSTANCE.env"

. "$HERE/ioc-ports.sh"
ioc_ports_resolve

[ -n "$IOC_PREFIX" ] || IOC_PREFIX="$INSTANCE:"
[ -n "$IOC_STATE" ] || IOC_STATE="/var/lib/${PN}/$INSTANCE"
[ -n "$PROCSERV_ARGS" ] || PROCSERV_ARGS="-A"
export IOC_PREFIX IOC_STATE

# The EPICS service ports stay dynamic unless the instance pins them. rsrv
# reads EPICS_CA_SERVER_PORT when its server starts, pvAccess reads
# EPICS_PVAS_SERVER_PORT, so exporting here is early enough.
if [ -n "$CA_PORT" ]; then
    export EPICS_CA_SERVER_PORT="$CA_PORT"
fi
if [ -n "$PVA_PORT" ]; then
    export EPICS_PVAS_SERVER_PORT="$PVA_PORT"
fi

mkdir -p "$IOC_STATE" "$IOC_RUN_DIR"
cd "$HERE/${IOC_PATH}"

# Optional hook, e.g. an external device simulator bound to $APP_PORT_1. It runs
# as a sibling process in this service's cgroup, so systemd stops it with the
# IOC.
[ -r "$HERE/${IOC_PATH}/ioc-start.pre" ] && . "$HERE/${IOC_PATH}/ioc-start.pre"

${EPICS_IOC_START_PRE}

# -I makes procServ record PID and endpoints, so the running instance can be
# found without knowing the port in advance.
exec procServ -f -L - -I "$IOC_RUN_DIR/$INSTANCE.info" -P "$PS_PORT" $PROCSERV_ARGS @IOC_EXEC@
IOCSTARTEOF

    # Point procServ at either the IOC executable or the st.cmd directly. The
    # placeholder keeps the shell metacharacters out of the BitBake heredoc.
    if [ -n "${IOC_APP_NAME}" ]; then
        ioc_exec="\"\$HERE/bin/${EPICS_TARGET_ARCH}/${IOC_APP_NAME}\" ${IOC_ST_CMD}"
    else
        ioc_exec="./${IOC_ST_CMD}"
    fi
    sed -i "s,@IOC_EXEC@,${ioc_exec}," ${install_dir}/ioc-start.sh

    # An st.cmd executed directly through its shebang must be executable.
    [ -f "${install_dir}/${IOC_PATH}/${IOC_ST_CMD}" ] && \
        chmod 0755 ${install_dir}/${IOC_PATH}/${IOC_ST_CMD}

    chmod 0755 ${install_dir}/ioc-ports.sh ${install_dir}/ioc-start.sh

    cat > ${install_dir}/ioc-instance-add <<'IOCADDEOF'
#!/bin/sh
# Generated by epics-ioc-systemd.bbclass -- do not edit.
# Create an instance env file with the next free IOC_INSTANCE_INDEX.
set -e

[ -n "$1" ] || { echo "usage: $0 <instance-name>" >&2; exit 2; }

HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/ioc-ports.sh"

_name="$1"
_target="${EPICS_IOC_ENV_DIR}/$_name.env"
[ -e "$_target" ] && { echo "$_target already exists" >&2; exit 1; }

_index="$(ioc_ports_next)"
cat > "$_target" <<EOF
IOC_INSTANCE_INDEX=$_index
IOC_PREFIX=$_name:
IOC_STATE=/var/lib/${PN}/$_name
EOF
echo "created $_target (IOC_INSTANCE_INDEX=$_index)"
IOCADDEOF
    chmod 0755 ${install_dir}/ioc-instance-add

    # Instance env template.
    cat > ${env_dir}/example.env <<EOF
# Per-instance configuration for ${PN}. Copy to <name>.env, adjust, then
#   systemctl enable --now '${PN}@<name>'
# IOC_INSTANCE_INDEX is unique across every IOC on this target: it picks the
# console port ${EPICS_IOC_PORT_BASE} + 10*index. See docs/port-allocation.md.
IOC_INSTANCE_INDEX=0
IOC_PREFIX=example:
IOC_STATE=/var/lib/${PN}/example

# CA_PORT=...       # pin the CA server port (recommended: base + 10*index + 3);
# PVA_PORT=...      # pin the PVA server port (recommended: base + 10*index + 4);
#                   # leave both unset to let EPICS assign them dynamically
# PS_PORT=...       # override the procServ console port
# APP_PORT_1=...    # override the primary application port
# APP_PORT_2=...    # override the secondary application port
EOF

    for instance in ${EPICS_IOC_INSTANCE_ENVS}; do
        install -m 0644 "$instance" "${env_dir}/$(basename "$instance")"
    done

    if [ "${EPICS_IOC_MULTI_INSTANCE}" = "1" ]; then
        cat > ${unit_dir}/${PN}@.service <<EOF
[Unit]
Description=%p IOC instance %i
After=network.target

[Service]
Type=simple
EnvironmentFile=-${EPICS_IOC_ENV_DIR}/%i.env
ExecStart=${EPICS_INSTALL_BASE}/${EPICS_MODULE_NAME}/ioc-start.sh %i
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
EOF
    else
        cat > ${unit_dir}/${PN}.service <<EOF
[Unit]
Description=${PN} IOC
After=network.target

[Service]
Type=simple
ExecStart=${EPICS_INSTALL_BASE}/${EPICS_MODULE_NAME}/ioc-start.sh
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
EOF
    fi
}

FILES:${PN} += "${EPICS_IOC_ENV_DIR}"
